import { useState } from 'react'
import { PublicNav } from '../components/PublicNav'
import { Icon } from '../components/Icon'
import { navigate } from '../lib/router'
import type { Session } from '../lib/types'

const serviceImages = [
  ['Electrical & repairs', 'Professional repairs, plumbing, electrical work and home maintenance.', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1000&q=85'],
  ['Cleaning services', 'Trusted cleaning, laundry, deep cleaning and home support.', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=85'],
  ['Transport & cabs', 'Cabs, airport transfers, drivers and vehicle hire.', 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1000&q=85'],
]

export function HomePage({ session }: { session: Session | null }) {
  const [inviteOpen, setInviteOpen] = useState(false)
  const [reportOpen, setReportOpen] = useState(false)
  const [inviteSent, setInviteSent] = useState(false)
  const [reportSent, setReportSent] = useState(false)
  const openPortal = () => navigate(session ? `/app/${session.role}` : '/login/tenant')

  return <div className="public-site security-home">
    <PublicNav session={session} />
    <main>
      <section className="security-hero section"><div className="container security-hero__grid"><div className="security-hero__copy"><span className="eyebrow"><Icon name="shield" size={15} /> Security-first property living</span><h1>Know who is in your building. <span>Keep everyone connected.</span></h1><p>MongaLets keeps management and security informed about residents, guests and service visits — while making everyday life simpler for tenants and clients.</p><div className="security-hero__actions"><button className="button button--primary button--large" onClick={openPortal}>Open my portal <Icon name="arrow-right" size={18} /></button><button className="button button--secondary button--large" onClick={() => setInviteOpen(true)}>Invite a visitor <Icon name="plus" size={18} /></button></div><div className="security-proof"><span><Icon name="check" size={14} /></span><strong>Simple for residents.</strong><small>Clear for security. Accountable for management.</small></div></div><div className="homepage-hero-image"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=88" alt="Bright modern residential living space" /><div className="hero-image-badge"><span><Icon name="shield" size={15} /></span><div><strong>Security first</strong><small>Access stays controlled</small></div></div></div></div></section>

      <section className="security-focus section"><div className="container"><div className="section-heading section-heading--split security-heading"><div><span className="eyebrow">Just the essentials</span><h2>One calm system for security, access and resident needs.</h2></div><p>Know who is coming, approve access, report a problem and find trusted help — without unnecessary features getting in the way.</p></div><div className="security-feature-grid"><article className="security-feature security-feature--presence"><span className="feature-icon"><Icon name="users" size={22} /></span><small>01 · Building visibility</small><h3>Past, present & future presence</h3><p>Management and security can see who is currently inside, who has left, and who is expected next.</p><button onClick={openPortal}>Open security workspace <Icon name="arrow-right" size={15} /></button></article><article className="security-feature"><span className="feature-icon"><Icon name="key" size={22} /></span><small>02 · Visitor access</small><h3>Invite, share & approve</h3><p>Residents can invite someone themselves or approve an invitation. Security gets the right details before arrival.</p><button onClick={() => setInviteOpen(true)}>Create an invitation <Icon name="arrow-right" size={15} /></button></article><article className="security-feature"><span className="feature-icon"><Icon name="camera" size={22} /></span><small>03 · Complaints & reports</small><h3>Report it with a photo</h3><p>Raise complaints, incidents or maintenance reports in a few taps and attach photos when they help.</p><button onClick={() => setReportOpen(true)}>Raise a report <Icon name="arrow-right" size={15} /></button></article></div></div></section>

      <section className="homepage-photo-band section"><div className="container"><div className="photo-band-copy"><span className="eyebrow">Made for everyday living</span><h2>Useful, clear and human — not another complicated property system.</h2><p>Residents get the convenience they need. Security gets the visibility they need. Everyone else sees only what is relevant to them.</p><button className="button button--primary" onClick={openPortal}>Explore my experience <Icon name="arrow-right" size={16} /></button></div><div className="photo-band-images"><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85" alt="Comfortable modern apartment" /><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85" alt="People discussing a service" /></div></div></section>

      <section className="providers-section section" id="services"><div className="container"><div className="section-heading section-heading--center"><span className="eyebrow">Trusted service providers</span><h2>Help for the things around your home.</h2><p>Services stay practical: repairs, cleaning and transport — available without turning MongaLets into a marketplace or social app.</p></div><div className="provider-grid">{serviceImages.map(([title, text, image]) => <article className="homepage-provider-card" key={title}><img src={image} alt="" /><div className="homepage-provider-card__body"><span><Icon name={title.startsWith('Transport') ? 'map' : title.startsWith('Cleaning') ? 'sparkles' : 'tool'} size={20} /></span><h3>{title}</h3><p>{text}</p><button onClick={openPortal}>Explore providers <Icon name="arrow-right" size={14} /></button></div></article>)}</div></div></section>

      <section className="security-final section"><div className="container security-final__inner"><div><span className="eyebrow eyebrow--light">A simpler MongaLets</span><h2>Security sees the building. Residents feel the convenience.</h2><p>One focused experience for access, presence, reports and useful services.</p></div><button className="button button--cream button--large" onClick={openPortal}>Enter MongaLets <Icon name="arrow-right" size={17} /></button></div></section>
    </main>

    {inviteOpen && <div className="simple-modal-backdrop"><div className="simple-modal"><button className="icon-button" onClick={() => setInviteOpen(false)} aria-label="Close"><Icon name="close" size={19} /></button>{inviteSent ? <div className="modal-success"><span><Icon name="check" size={25} /></span><h3>Invitation ready</h3><p>The visitor invitation has been prepared for sharing and approval.</p><button className="button button--primary" onClick={() => { setInviteSent(false); setInviteOpen(false) }}>Done</button></div> : <><span className="modal-icon"><Icon name="plus" size={22} /></span><h3>Invite a visitor</h3><p>Add a visitor or service provider and choose when they should be expected.</p><label>Name<input placeholder="Visitor name" /></label><label>Visit date<input type="date" /></label><label>Purpose<select><option>Visitor</option><option>Service visit</option><option>Delivery</option></select></label><button className="button button--primary button--full" onClick={() => setInviteSent(true)}>Create invitation <Icon name="arrow-right" size={16} /></button></>}</div></div>}
    {reportOpen && <div className="simple-modal-backdrop"><div className="simple-modal"><button className="icon-button" onClick={() => setReportOpen(false)} aria-label="Close"><Icon name="close" size={19} /></button>{reportSent ? <div className="modal-success"><span><Icon name="check" size={25} /></span><h3>Report submitted</h3><p>Your report is now visible to the responsible team.</p><button className="button button--primary" onClick={() => { setReportSent(false); setReportOpen(false) }}>Done</button></div> : <><span className="modal-icon"><Icon name="camera" size={22} /></span><h3>Raise a report</h3><p>Tell us what happened. You can attach photos to make the report clearer.</p><label>Category<select><option>Maintenance</option><option>Security</option><option>Noise / neighbour</option><option>Other</option></select></label><label>What happened?<textarea rows={4} placeholder="Describe the issue briefly..." /></label><label>Photos<input type="file" accept="image/*" multiple /></label><button className="button button--primary button--full" onClick={() => setReportSent(true)}>Submit report <Icon name="arrow-right" size={16} /></button></>}</div></div>}
  </div>
}
