import { useState } from 'react'
import { Icon } from '../components/Icon'
const b='https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1100&q=85'
const maps=(q:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`
function Layout({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div className="role-section-page"><div className="role-section-head"><div><span className="eyebrow">Guest visit</span><h1>{title}</h1><p>{text}</p></div></div>{children}</div>}
export function GuestHome(){return <Layout title="Welcome, Grace" text="Your approved visit to Amina Njoki at Riverside Apartments."><article className="role-photo-card"><img src={b} alt="Riverside Apartments"/><div><span className="eyebrow">Host</span><h3>Amina Njoki · Apartment A5G</h3><p>Riverside Drive, Nairobi · 31 August 2026</p><a className="button button--secondary" href={maps('Riverside Apartments Nairobi')} target="_blank" rel="noreferrer">Directions</a></div></article><div className="role-stats">{[["Arrival","14:30","Today"],["Departure","17:30","Scheduled"],["Status","Approved","Ready at gate"],["Minors","1","Accompanying"]].map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div></Layout>}
export function GuestAccess(){const code='ML-GRACE-4931';const [open,setOpen]=useState(false);return <Layout title="Access Pass" text="Your visit credential is valid for the approved visit window."><section className="access-code-card"><span className="eyebrow">Active pass</span><strong>{code}</strong><img src={`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${code}`} alt="QR access pass"/><small>Riverside Apartments · A5G · Host Amina Njoki</small><div className="role-action-grid"><button className="button button--primary" onClick={()=>setOpen(true)}>Show QR</button><a className="button button--secondary" href={maps('Riverside Apartments Nairobi')} target="_blank" rel="noreferrer">Directions</a></div></section>{open&&<div className="ml-modal-backdrop"><div className="ml-modal"><div className="role-panel-head"><div><span className="eyebrow">Access credential</span><h2>{code}</h2><p>Present this QR at Gate 1.</p></div><button className="icon-button" onClick={()=>setOpen(false)}><Icon name="close"/></button></div><img className="modal-qr" src={`https://api.qrserver.com/v1/create-qr-code/?size=340x340&data=${code}`} alt="QR"/><button className="button button--primary" onClick={()=>setOpen(false)}>Close</button></div></div>}</Layout>}
export function GuestDetails(){return <Layout title="Visit Details" text="The details submitted for your approved visit."><section className="role-panel"><div className="profile-detail-grid">{[["Host","Amina Njoki"],["Building","Riverside Apartments"],["Apartment","A5G · 5th Floor"],["Purpose","Visit"],["Date","31 August 2026"],["Arrival","14:30"],["Departure","17:30"],["Accompanying minors","1"],["Notes","Meet host at lobby"]].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div></section></Layout>}
export function GuestGuide(){return <Layout title="Access Guide" text="Follow these simple steps when arriving at Riverside Apartments."><div className="guide-steps">{[['1','Arrive at gate','Use Gate 1 and have your QR ready.'],['2','Present QR','Show the access pass on your phone.'],['3','Security verifies','Security confirms host, apartment and validity.'],['4','Enter building','Follow lobby and lift signs.'],['5','Follow host instructions','Proceed to Apartment A5G.']].map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><article className="role-photo-card"><img src={b} alt="Building gate"/><div><h3>Gate 1 · Security desk</h3><p>Riverside Drive, Nairobi · Security available 24/7</p><a className="button button--secondary" href={maps('Riverside Apartments Nairobi')} target="_blank" rel="noreferrer">Directions</a></div></article></Layout>}
