import { Icon } from '../components/Icon'
const img='https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1100&q=85'
type Row=[string,string,string,string]
function Layout({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div className="role-section-page"><div className="role-section-head"><div><span className="eyebrow">Platform workspace</span><h1>{title}</h1><p>{text}</p></div></div>{children}</div>}
function Stats({items}:{items:Row[]}){return <div className="role-stats">{items.map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div>}
function List({items}:{items:Row[]}){return <div className="role-list">{items.map(x=><button className="role-list-row" key={x[0]}><span className="role-list-icon role-tone-info"><Icon name={x[3] as any} size={17}/></span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><b className="role-status role-status--good">{x[2]}</b></button>)}</div>}
const propertyRows:Row[]=[["Gate 1 security team","2 guards · Shift 06:00–18:00","On duty","shield"],["People currently inside","18 residents, guests and providers","Live","users"],["Failed access attempt","Gate 2 · Credential expired","Review","alert"]]
const peopleRows:Row[]=[["Amina Njoki","Tenant · A5G · Entered 08:14","Inside","users"],["Grace Wanjiku","Guest · A5G · Entered 14:31","Inside","key"],["Moses K.","Provider · Plumbing · B2","Inside","tool"],["Daniel Mwangi","Security · Gate 1","On duty","shield"]]
const visitRows:Row[]=[["Moses Plumbing · A5G","Riverside · Amina · 31 Aug 16:00 · Access valid","Confirmed","tool"],["Spark Electrical · B2","Westlands · James · 1 Sep 11:00","Pending","tool"],["CleanPro · C4","Riverside · Faith · 2 Sep 14:30","Scheduled","tool"]]
export function Management({section}:{section:string}){
 if(section==='security')return <Layout title="Security" text="Guards, current people, failed access and incidents for Riverside Apartments."><Stats items={[["Guards on duty","4","Today","shield"],["People inside","18","Live","users"],["Failed attempts","2","Last 24 hours","alert"],["Incidents","1","Review","shield"]]}/><section className="role-panel"><List items={propertyRows}/></section></Layout>
 if(section==='people-presence')return <Layout title="People & Presence" text="Residents, guests, providers and security connected to your property."><section className="role-panel"><List items={peopleRows}/></section></Layout>
 if(section==='visitor-access')return <Layout title="Visitor Access" text="Approve, reject, extend and revoke property visits."><section className="role-panel"><List items={[["Grace Wanjiku","Host Amina · A5G · Today 14:30–17:30","Approved","users"],["Peter Otieno","Host Unit C2 · Tomorrow 10:00–12:00","Pending","users"],["Faith Njeri","A5G · 29 Aug · Completed","Completed","check"]]}/></section></Layout>
 if(section==='requests')return <Layout title="Requests" text="Property service requests and operational status."><section className="role-panel"><List items={visitRows}/></section></Layout>
 if(section==='service-providers')return <Layout title="Service Providers" text="Providers available to work at Riverside Apartments. Final pricing follows quotation."><div className="role-service-grid">{['Moses Plumbing','CleanPro Kenya','Spark Electrical'].map(x=><article className="service-card" key={x}><img src={img} alt=""/><div><span className="eyebrow">Verified · 4.8 ★</span><h3>{x}</h3><p>Service provider · Available</p><strong>Indicative pricing</strong><small>Final price follows quotation</small><button className="button button--secondary">View profile</button></div></article>)}</div></Layout>
 return <Layout title="Riverside Apartments" text="Manage apartments, residents, access, visitors, requests and services."><Stats items={[["Apartments","48","44 occupied","grid"],["Residents","92","Property","users"],["Visitors today","18","6 inside","users"],["Service visits","5","Today","tool"]]}/><article className="role-photo-card"><img src={img} alt="Building"/><div><span className="eyebrow">Property</span><h3>Riverside Apartments</h3><p>Riverside Drive · Nairobi · 48 apartments</p><button className="button button--secondary">Manage building</button></div></article></Layout>
}
export function Admin({section}:{section:string}){
 if(section==='security')return <Layout title="Security" text="Platform-wide authentication, roles, access events and suspicious activity."><Stats items={[["Failed access","17","24 hours","alert"],["Verifications","2,418","This month","check"],["Incidents","8","Review","shield"],["Active credentials","3,842","Platform","key"]]}/><section className="role-panel"><List items={[["Failed authentication","3 accounts · Multi-property","Review","shield"],["Revoked credential","ML-X7Q · Riverside","Revoked","key"],["Verification history","2,418 checks this month","Healthy","check"]]}/></section></Layout>
 if(section==='people-presence')return <Layout title="People & Presence" text="Platform-wide people directory with building, role and access filters."><section className="role-panel"><List items={peopleRows}/></section></Layout>
 if(section==='service-visits'||section==='requests')return <Layout title="Service Visits" text="Track provider visits across buildings, apartments, residents and access."><section className="role-panel"><List items={visitRows}/></section></Layout>
 if(section==='service-providers')return <Layout title="Service Providers" text="Provider management, verification, properties served and financial status."><section className="role-panel"><List items={[["Moses Plumbing","8 properties · 96 jobs · 4.8 ★","Verified","tool"],["CleanPro Kenya","12 properties · 184 jobs · 4.9 ★","Verified","tool"],["Spark Electrical","7 properties · 138 jobs · 4.8 ★","Verified","tool"]]}/></section></Layout>
 if(section==='reviews')return <Layout title="Reviews" text="Customer feedback across providers, services and properties."><section className="role-panel"><List items={[["Amina Njoki · 5 ★","Plumbing · Moses Plumbing · Riverside A5G","Published","star"],["James Kariuki · 5 ★","Electrical · Westlands B2","Published","star"],["Faith Njeri · 4 ★","Cleaning · Riverside C4","Published","star"]]}/></section></Layout>
 if(section==='finance')return <Layout title="Finance" text="Platform revenue, gross service volume, fees and provider liabilities."><Stats items={[["Gross service volume","KSh 185,000","August","chart"],["Platform fees","KSh 9,250","5%","wallet"],["Payment fees","KSh 3,700","August","wallet"],["Provider liabilities","KSh 172,050","Payable","wallet"]]}/><section className="role-panel"><List items={[["Moses Plumbing","Gross KSh 48,000 · Fees KSh 3,360 · Payable KSh 44,640","Pending","wallet"],["CleanPro Kenya","Gross KSh 36,000 · Fees KSh 2,520 · Payable KSh 33,480","Processing","wallet"]]}/></section></Layout>
 return <Layout title="Platform Overview" text="Manage the complete MongaLets ecosystem."><Stats items={[["Buildings","24","Active","grid"],["Apartments","1,284","Platform","grid"],["Tenants","1,946","Active","users"],["Providers","138","Verified","tool"],["Requests","684","This month","briefcase"],["Revenue","KSh 428,600","August","wallet"]]}/><section className="role-panel"><h2>Building directory</h2><List items={[["Riverside Apartments","48 apartments · 92% occupied","Healthy","grid"],["Westlands Heights","60 apartments · 91% occupied","Active","grid"],["Kilimani Court","72 apartments · 89% occupied","Active","grid"]]}/></section></Layout>
}
