import { useState } from 'react'
import { Icon } from '../components/Icon'
const b='https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=85',p='https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=900&q=85',e='https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=85',c='https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=85'
function Layout({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div className="role-section-page"><div className="role-section-head"><div><span className="eyebrow">Provider workspace</span><h1>{title}</h1><p>{text}</p></div></div>{children}</div>}
function Stats({v}:{v:string[][]}){return <div className="role-stats">{v.map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div>}
function List({items}:{items:string[][]}){const [x,setX]=useState<string[]|null>(null);return <><div className="role-list">{items.map(i=><button className="role-list-row" key={i[0]} onClick={()=>setX(i)}><span className="role-list-icon role-tone-info"><Icon name={i[3]||'tool'} size={17}/></span><div><strong>{i[0]}</strong><small>{i[1]}</small></div><b className="role-status role-status--good">{i[2]}</b></button>)}</div>{x&&<div className="ml-modal-backdrop"><div className="ml-modal"><div className="role-panel-head"><div><span className="eyebrow">Job details</span><h2>{x[0]}</h2><p>{x[1]}</p></div><button className="icon-button" onClick={()=>setX(null)}><Icon name="close"/></button></div><div className="profile-detail-grid"><div><small>Status</small><strong>{x[2]}</strong></div><div><small>Building</small><strong>Riverside Apartments</strong></div><div><small>Apartment</small><strong>A5G · 5th Floor</strong></div><div><small>Resident</small><strong>Amina Njoki</strong></div></div><button className="button button--primary" onClick={()=>setX(null)}>Close</button></div></div>}</>}
export function ProviderHome(){return <Layout title="Provider Overview" text="Your jobs, schedule, earnings and customer rating at a glance."><Stats v={[["Today's jobs","3","1 in progress"],["Pending requests","4","2 new"],["Completed jobs","96","August"],["Gross earnings","KSh 48,000","August"]]}/><ProviderJobs/></Layout>}
export function ProviderJobs(){return <Layout title="My Jobs" text="Property, apartment, resident, appointment and access information for every job."><section className="role-panel"><List items={[["Plumbing repair · A5G","Riverside Apartments · 5th Floor · Amina Njoki · Today 16:00–17:00","Accepted","tool"],["Electrical inspection · B2","Westlands Heights · James Kariuki · Tomorrow 11:00–12:00","Pending","tool"],["Cleaning · C4","Riverside Apartments · Faith Njeri · 2 Sep 14:30","Scheduled","tool"]]}/></section><article className="role-photo-card"><img src={b} alt="Building"/><div><span className="eyebrow">Next job</span><h3>Riverside Apartments · Apartment A5G</h3><p>Amina Njoki · Plumbing repair · 16:00–17:00</p><div className="role-action-grid"><button className="button button--primary">Start job</button><button className="button button--secondary">Complete job</button></div></div></article></Layout>}
export function ProviderServices(){return <Layout title="My Services" text="Manage categories, portfolio, indicative prices, availability and service areas."><div className="role-service-grid">{[['Plumbing',p,'From KSh 1,500'],['Emergency repairs',p,'From KSh 2,500'],['Electrical fixtures',e,'From KSh 1,800']].map(x=><article className="service-card" key={x[0]}><img src={x[1]} alt=""/><div><h3>{x[0]}</h3><p>Professional service and maintenance.</p><strong>{x[2]}</strong><small>Final pricing subject to quotation</small><button className="button button--secondary">Edit service</button></div></article>)}</div><button className="button button--primary">Add service</button></Layout>}
export function ProviderFinance(){return <Layout title="Finance" text="Only your service earnings, fees and payouts are visible here."><Stats v={[["Gross earnings","KSh 48,000","August"],["Platform fees","KSh 2,400","5%"],["Payment fees","KSh 960","August"],["Net earnings","KSh 44,640","Payable"]]}/><section className="role-panel"><List items={[["August payout","12 jobs · Gross KSh 48,000 · Fees KSh 3,360 · Net KSh 44,640","Pending","wallet"],["July payout","18 jobs · Net KSh 61,200","Paid","check"]]}/></section></Layout>}
export function ProviderReviews(){return <Layout title="Reviews" text="Customer feedback connected to your completed jobs."><Stats v={[["Overall rating","4.8 ★","128 reviews"],["5 stars","82%","Distribution"],["4 stars","13%","Distribution"],["3 or below","5%","Attention"]]}/><section className="role-panel"><List items={[["Amina Njoki · 5 ★","Plumbing repair · 31 Aug","Published","star"],["James Kariuki · 5 ★","Electrical inspection · 28 Aug","Published","star"],["Faith Njeri · 4 ★","Service visit · 24 Aug","Published","star"]]}/></section></Layout>}
