import { HomePage } from './pages/HomePage'
import { LoginPage } from './pages/LoginPage'
import { SecurityPortalPage } from './pages/SecurityPortalPage'
import { RoleWorkspacePage } from './pages/RoleWorkspacePage'
import { PortalEnhancements } from './components/PortalEnhancements'
import { VisitorInvitePage } from './pages/VisitorInvitePage'
import { Toast } from './components/Toast'
import { useRoute, navigate } from './lib/router'
import { useSession } from './lib/session'
export default function App(){const route=useRoute();const{session,syncedFromAnotherTab}=useSession();if(route.page==='home')return <><HomePage session={session}/><Toast visible={syncedFromAnotherTab} message="Your session was updated from another tab."/></>;if(route.page==='login')return <><LoginPage initialRole={route.role} session={session}/><Toast visible={syncedFromAnotherTab} message="Your session was updated from another tab."/></>;if(route.page==='invite')return <VisitorInvitePage tenantCode={route.section}/>;if(route.page==='portal'){if(!session||session.role!==route.role)return <div className="route-guard"><div className="route-guard__card"><span>ML</span><h1>Secure workspace</h1><p>Sign in with the correct role to access this MongaLets portal.</p><button className="button button--primary" onClick={()=>navigate(`/login/${route.role}`)}>Continue to login</button></div></div>;if(route.section)return <><RoleWorkspacePage role={route.role} section={route.section} session={session}/><Toast visible={syncedFromAnotherTab} message="Your session was updated from another tab."/></>;return <><SecurityPortalPage role={route.role} session={session}/><PortalEnhancements role={route.role} session={session}/></>}return <div className="not-found"><div><span>404</span><h1>This page is not part of the property.</h1><p>The link may have moved or the workspace is not available.</p><button className="button button--primary" onClick={()=>navigate('/')}>Return home</button></div></div>}
